#:schema node_modules/wrangler/config-schema.json
name = "agent8"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-11"
pages_build_output_dir = "./build/client"
send_metrics = false

[durable_objects]
bindings = [
  { name = "ACCESS_LOG_BUFFER", class_name = "AccessLogBuffer", script_name = "agent8-access-log-worker" }
]

