#:schema node_modules/wrangler/config-schema.json
name = "agent8"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
send_metrics = false